### ISSUE TITLE
Can't retrieve a comment's post title

### ISSUE THREAD

**Issue by frissyn** [frissyn/ReplCustoms#1]
Under the "Recent Comments" section of a user's profile page, an expandable menu that contains the recent comments and the post that they came from doesn't display the title as intended.

**Code snippet from [`user-output.html`](https://github.com/IreTheKID/Repl-Customs/blob/master/templates/user-output.html)**
```html
<div class="collapsible-header">
        <a href="{{comment.url}}">
        <i class="material-icons">call_made</i></a>
         <b>[⬆️&nbsp;{{comment.votes}}]</b> From: <b>{{comment.post}}</b>
</div>
<div class="collapsible-body" style="background-color: white">
        <div class="center-custom pd-high">
                <span style="margin: 16px; padding: 16px;">
                {{comment.content[:300]}}<b>...</b>
                </span>
        </div>
</div>
```

The `{{ comment.post }}` Flask code block is supposed to return the comment's post title.

**Comment by AmazingMech2418** [comment]
All it was really was that the posts and comments were using the same API which is the one for the posts.
