### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by thewaydev** [frissyn/ReplCustoms#12]
When you look up a post, you could make it so you can go back to the homepage. Because after you look up a post, your stuck in that page. So a button that allows you to go back to the main page should work.

**Comment by PotentialStyx** [comment]
I'll make a pr with some changes I've made that add this
Test them here: https://repl-customs.codemonkey51.repl.co/ (tell me if any links aren't there)

**Comment by PotentialStyx** [comment]
I linked it in #14

**Comment by frissyn** [comment]
add a back button?

**Comment by PotentialStyx** [comment]
I thought that my or made the icon link to the home page is that good?

**Comment by thewaydev** [comment]
When i click on the icon, it does nothing.

**Comment by PotentialStyx** [comment]
Yes ik I'm going to check my pr and some other stuff

**Comment by PotentialStyx** [comment]
@FunnyLamma just checked the repl hasnt been pulled but the code here on github does have the button working

**Comment by thewaydev** [comment]
Okay,
