### ISSUE TITLE
Async is used Synchronously

### ISSUE THREAD

**Issue by ghost** [frissyn/ReplCustoms#37]
The server uses async functions, like the one to get leaderboard data,  synchronously, and waits for them to complete before sending them to the client. This makes requests/responses very slow. A better solution (IMO) would be some sort of stream or P2P HTTP endpoint where you send data as it comes, and then show a loading screen while the leaderboard is loading.

**Comment by PotentialStyx** [comment]
We already have something like that for users and posts where it has a loading screen while the request is being made so something like that? (I'm talking about the rework rn)

**Comment by PotentialStyx** [comment]
I implemented a loading screen for the leaderboard in the rework try it out here: [leaderboard](https://rc.irethekid.repl.co/goto/lboard)

**Comment by frissyn** [comment]
Like codemonkey said, we have a loading page already implemented in the rework which is scheduled to be released by the end of the month. :)
