### ISSUE TITLE
BUG: Sometimes searching doesn't happen

### ISSUE THREAD

**Issue by Minion3665** [frissyn/ReplCustoms#5]
From my testing, it appears that searching does not occur unless you click the text on the 'get results' button. Simply clicking on the other spaces of the button does not submit the content.

Expected result: 
The form is submitted

Actual result:
The form is not submitted, but notably the darker green onclick effect still triggers

How to reproduce:
- Go to https://repl-customs-v1--irethekid.repl.co/app
- Enter a name
- Press the search button on the edge (not in the middle where the text is)

**Comment by Commander07** [comment]
This has already been fixed but the update has not yet gone live on repl.it if I'm correct.

**Comment by Commander07** [comment]
I seem to have found the problem as the button fix was not applied correctly as the "result-button" class should be applied to the <input> and not the <i>.

**Comment by frissyn** [comment]
Bugfix has gone live as of 10:22 am on 5/25/2020.
