### ISSUE TITLE
Recent comments won't load.

### ISSUE THREAD

**Issue by thewaydev** [frissyn/ReplCustoms#6]
I don't know if this is a problem for everyone, but it won't show me recent comments when looking at a profile on Repl-Customs. It says "A problem occurred, please try again later".

**Comment by thewaydev** [comment]
I am trying to find a solution to this error

**Comment by firefish111** [comment]
@FunnyLamma I'm getting the same error too... I think it's everybody

**Comment by PotentialStyx** [comment]
I think this has been fixed

**Comment by firefish111** [comment]
@Codemonkey51 Comment names aren't working.... maybe on the 11pm friday update? idk
![image](https://user-images.githubusercontent.com/33234914/86953495-6dadbf80-c14c-11ea-9b38-ad33ecfbdfb4.png)

**Comment by firefish111** [comment]
@IreTheKID Hm.. what happened to the update? 
![image](https://user-images.githubusercontent.com/33234914/87241428-e47fdc80-c41a-11ea-834f-09d8a960adda.png)

**Comment by PotentialStyx** [comment]
Ummm idk but I do know that the rework is up (not officially released) but here is the link: [link](https://rc--irethekid.repl.co)

**Comment by firefish111** [comment]
Wow that looks re-work looks amazing

**Comment by PotentialStyx** [comment]
This was fixed in the rework
